### PR TITLE
Download button to wiki link

### PR DESCRIPTION
**Pull request by jonaharagon**
Changed the big download button to a link to the wiki page on how to install, so people are forced to read the instructions instead of downloading and asking for help :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by jonaharagon** [comment]
Also includes #40 I guess

**Comment by JZ6** [comment]
to be considered

**Comment by JZ6** [comment]
better idea, add an installtion instructions text below the button to link to the wiki

**Comment by jonaharagon** [comment]
The wiki link also includes download links to both the master zip and the develop zip though, which is why I thought it could serve as a general Get Started link.

**Pull request closed without merging**
